#!/usr/bin/env bash

# Orchestrator (CLI). The interactive menus live in ./init.sh; both entry
# points share the canonical actions defined in lib/steps.sh, so their
# results can no longer diverge.

set -uo pipefail
source lib/common.sh
source lib/api.sh
source lib/steps.sh

usage() {
    echo "Usage: $0 <detect|decide|search|check|all|partition|install|layout|clean>"
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

cmd_search() {
    local q="$1" json
    json=$(search_pkg "$q") || {
        error "Search failed"
        return 1
    }
    echo "$json" | grep -oE '"pkgname": "[^"]*"|"pkgver": "[^"]*"|"repo": "[^"]*"'
}

# Interactive layout editor: builds output/layout.txt with custom partitions
# (separate /home, custom sizes...). Non-interactive: shows the current plan.
cmd_layout() {
    if [[ ! -f output/facts.txt ]]; then
        error "output/facts.txt not found — run './main.sh detect' first"
        return 1
    fi
    source output/facts.txt
    source decide/partition.sh

    if [[ ! -t 0 ]]; then
        warn "Not a terminal — showing the current layout instead"
        plan_partitions
        return 0
    fi

    # Start from an existing layout when there is one
    local swap="auto" root_fs="" extras=()
    local mp="" f="" size="" ans=""
    if [[ -f output/layout.txt ]]; then
        info "Editing existing output/layout.txt"
        while read -r mp f size; do
            [[ "$mp" == \#* || -z "$mp" ]] && continue
            case "$mp" in
            "[swap]") swap="$size" ;;
            "/") root_fs="$f" ;;
            /*) extras+=("$mp|$f|$size") ;;
            esac
        done <output/layout.txt
    fi

    # 1. Swap
    while true; do
        printf 'Swap? [auto / size like 8G / none] (default: %s): ' "${swap:-none}"
        read -r ans
        [[ -n "$ans" ]] && swap="$ans"
        if [[ "$swap" =~ ^(auto|none)$ || "$swap" =~ ^[0-9]+[MG]$ ]]; then
            break
        fi
        warn "Invalid swap: $swap (use auto, none or a size like 8G)"
    done

    # 2. Root filesystem
    [[ -z "$root_fs" ]] && root_fs=$(default_fs)
    while true; do
        printf 'Root filesystem? [btrfs/ext4] (default: %s): ' "$root_fs"
        read -r ans
        [[ -n "$ans" ]] && root_fs="$ans"
        if [[ "$root_fs" == "btrfs" || "$root_fs" == "ext4" ]]; then
            break
        fi
        warn "Invalid filesystem: $root_fs (use btrfs or ext4)"
    done

    # 3. Extra data partitions
    while true; do
        printf 'Add a data partition? mount point (e.g. /home) or empty to finish: '
        read -r mp
        [[ -z "$mp" ]] && break
        if [[ "$mp" != /* || "$mp" == "/" || "$mp" == "/efi" ]]; then
            warn "Invalid mount point: $mp (must be like /home)"
            continue
        fi
        printf '  Filesystem [btrfs/ext4] (default: %s): ' "$root_fs"
        read -r f
        [[ -z "$f" ]] && f="$root_fs"
        if [[ "$f" != "btrfs" && "$f" != "ext4" ]]; then
            warn "Invalid filesystem: $f (use btrfs or ext4)"
            continue
        fi
        printf '  Size in G (e.g. 100, or rest): '
        read -r size
        if ! [[ "$size" =~ ^[0-9]+$ || "$size" == "rest" ]]; then
            warn "Invalid size: $size (use a number of GB or rest)"
            continue
        fi
        extras+=("$mp|$f|${size}G")
    done

    # 4. Write layout.txt
    {
        echo "# Custom layout generated by ./main.sh layout — edit freely"
        echo "# Format: <mount> <filesystem> <size|rest>  (the boot partition is automatic)"
        if [[ "$swap" == "auto" ]]; then
            echo "[swap] linux-swap auto"
        elif [[ "$swap" != "none" ]]; then
            echo "[swap] linux-swap $swap"
        fi
        for e in "${extras[@]}"; do
            IFS='|' read -r mp f size <<<"$e"
            echo "$mp $f $size"
        done
        echo "/ $root_fs rest"
    } >output/layout.txt
    log "Layout written to output/layout.txt"
    plan_partitions
}

case "$1" in
detect) step_detect ;;
decide) build_package_list ;;
search) cmd_search "$2" ;;
check) validate_packages ;;
all)
    step_detect && build_package_list && validate_packages
    ;;
partition) plan_partitions ;;
install) generate_install ;;
layout) cmd_layout ;;
clean)
    rm -f output/*.txt output/*.md output/install.sh
    info "Output cleaned"
    ;;
*)
    usage
    exit 1
    ;;
esac
