#!/usr/bin/env bash

#Installer

set -euo pipefail

if [[ "$(systemd-detect-virt)" == "none" ]]; then
    echo "Refusing to run outside a VM" >&2
    exit 1
fi

build_install_plan() {
    build_partitions # fills DISK, FS_ROOT, SWAP_GB, PART_EFI, PART_SWAP, PART_ROOT

    local ucode=""
    case "${CPU_VENDOR:-uknown}" in
    amd) ucode="amd-ucode" ;;
    intel) ucode="intel-ucode" ;;
    esac

    local bootloader_install="grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB"
    [[ "${FIRMAWARE:-bios}" == "bios" ]] && bootloader_install="grub-install --target=i386-pc $DISK"

    cat <<EOF
#!/usr/bin/env bash
# Generated by cleiva_arch_installer
set -euo pipefail
...guard...

# 1. Partitions (${FIRMWARE:-bios})
sgdisk --zap-all "$DISK"
sgdisk -n1:0+512M -t1:ef00 "$DISK" # EFI
sgdisk -n2:0+${SWAP_GB} -t2:8200 "$DISK" # SWAP
sgdisk -n3:0:0 -t3:8300 "$DISK" # root (rest)

# 2. Filesystems
mkfs.fat -F32 "$PART_EFI"
mkswap "$PART_SWAP"
mkfs.btrfs -f "$PART_ROOT"

# 3. Mount
mount "$PART_ROOT" /mnt
mount --mkdir "$PART_EFI" /mnt/efi
swapon "$PART_SWAP"

# 4. Base system
pacstrap -K /mnt base linux linux-firmware $ucode networkmanager sudo git nano grub efibootmgr

# 5. fstab
genfstab -U /mnt/etc/fstab

# 6. Chroot configuration
arch-chroot /mnt /bin/bash -c '
set -e
ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo myhost > /etc/hostname
systemctl enable NetworkManager
$bootloader_install
grub-mkconfig -o /boot/grub/grub.cfg
'
EOF
}
