#!/usr/bin/env bash
# decide/install.sh
# Generates the installation commands (run in QEMU, never on real hardware)

build_install_plan() {
    # Needs facts (./main.sh detect) and the decided package list (./main.sh decide)
    if [[ ! -f output/packages.txt ]]; then
        error "output/packages.txt not found — run './main.sh decide' first"
        return 1
    fi
    if [[ -z "${DISK_NAME:-}" || "${DISK_NAME:-}" == "none" ]]; then
        error "No disk detected — run './main.sh detect' first"
        return 1
    fi

    build_partitions >/dev/null # fills LAYOUT_ENTRIES, DISK, FS_ROOT, PART_*

    local ucode=""
    case "${CPU_VENDOR:-unknown}" in
    amd) ucode="amd-ucode" ;;
    intel) ucode="intel-ucode" ;;
    esac

    # Check if multilib is needed (Wine, Steam, or any lib32-* packages)
    local need_multilib=0
    if grep -qE '^(wine|steam|lib32-)' output/packages.txt; then
        need_multilib=1
    fi

    # Decided packages (from the tree) + what any installer needs
    local pkgs extra="linux-firmware grub" entry=""
    pkgs=$(tr '\n' ' ' < output/packages.txt)
    [[ "${FIRMWARE:-uefi}" == "uefi" ]] && extra+=" efibootmgr"
    if [[ "$FS_ROOT" == "btrfs" ]]; then
        extra+=" btrfs-progs"
    else
        # any btrfs data partition needs the tools too
        for entry in "${LAYOUT_ENTRIES[@]}"; do
            if [[ "$entry" == *"|btrfs|"* ]]; then
                extra+=" btrfs-progs"
                break
            fi
        done
    fi

    # Locale/hostname/timezone: from facts.txt or env, safe defaults otherwise
    local tz="${TIMEZONE:-UTC}"
    local locale="${LOCALE:-en_US.UTF-8}"
    local hostname="${HOST_NAME:-arch}"

    local bootloader_install="grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB"
    [[ "${FIRMWARE:-uefi}" == "bios" ]] && bootloader_install="grub-install --target=i386-pc $DISK"

    local services="NetworkManager"
    [[ "${HAS_BLUETOOTH:-no}" == "yes" ]] && services+=" bluetooth"
    [[ "${HAS_BATTERY:-no}" == "yes" ]] && services+=" tlp"
    
    # Add docker service if docker is in package list
    if grep -q '^docker$' output/packages.txt; then
        services+=" docker"
    fi

    # --- Partition commands, data-driven from the layout ---
    local suffix; suffix=$(partition_suffix)
    local sgdisk_plan="" mkfs_plan="" mount_plan=""
    local i=1 mp="" f="" size="" part="" cmd=""

    # mount / first: children need the root mounted before them
    for entry in "${LAYOUT_ENTRIES[@]}"; do
        IFS='|' read -r mp f size <<<"$entry"
        if [[ "$mp" == "/" ]]; then
            printf -v mount_plan '%s%s' "$mount_plan" "mount \"$DISK${suffix}${i}\" /mnt
"
        fi
        i=$((i + 1))
    done

    i=1
    for entry in "${LAYOUT_ENTRIES[@]}"; do
        IFS='|' read -r mp f size <<<"$entry"
        part="$DISK${suffix}${i}"

        printf -v sgdisk_plan '%s%s' "$sgdisk_plan" "sgdisk -n${i}:0:$(sgdisk_size "$size") -t${i}:$(type_code_for "$mp") \"$DISK\"   # ${mp}
"

        cmd=$(mkfs_cmd_for "$f")
        if [[ -n "$cmd" ]]; then
            printf -v mkfs_plan '%s%s' "$mkfs_plan" "$cmd \"$part\"
"
        fi

        case "$mp" in
        "[swap]") printf -v mount_plan '%s%s' "$mount_plan" "swapon \"$part\"
" ;;
        "/") : ;; # mounted first
        "/efi") printf -v mount_plan '%s%s' "$mount_plan" "mount --mkdir \"$part\" /mnt/efi
" ;;
        "[bios_grub]") : ;; # grub writes here, nothing to mount
        *) printf -v mount_plan '%s%s' "$mount_plan" "mount --mkdir \"$part\" /mnt${mp}
" ;;
        esac
        i=$((i + 1))
    done

    cat <<EOF
#!/usr/bin/env bash
# Generated by cleiva_arch_installer — review it before running!
set -euo pipefail

# Safety: only run inside a VM
if [[ "\$(systemd-detect-virt)" == "none" ]]; then
    echo "Refusing to run outside a VM" >&2
    exit 1
fi

# Safety: never partition removable media (e.g. the USB stick you booted from)
if [[ "\$(lsblk -d -n -o RM "$DISK" 2>/dev/null)" == "1" ]]; then
    echo "Refusing: $DISK looks like removable media" >&2
    exit 1
fi

# 1. Partitions (${FIRMWARE:-uefi})
sgdisk --zap-all "$DISK"
${sgdisk_plan}
# 2. Filesystems
${mkfs_plan}
# 3. Mount
${mount_plan}
# 4. Base system + decided packages
pacstrap -K /mnt ${pkgs}${extra}

# 5. fstab (all mounts above must exist)
genfstab -U /mnt >> /mnt/etc/fstab

# 6. Chroot configuration
arch-chroot /mnt /bin/bash <<'CHROOT_EOF'
set -euo pipefail
ln -sf /usr/share/zoneinfo/$tz /etc/localtime
hwclock --systohc
echo "$locale UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=$locale" > /etc/locale.conf
echo "$hostname" > /etc/hostname
EOF

    # Add multilib if needed
    if ((need_multilib)); then
        cat <<'EOF'
# Enable multilib repository for 32-bit support (Wine, Steam)
if ! grep -q "^\[multilib\]" /etc/pacman.conf; then
    printf "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
    pacman -Sy --noconfirm
fi
EOF
    fi

    cat <<EOF
systemctl enable $services
$bootloader_install
grub-mkconfig -o /boot/grub/grub.cfg
echo "== Set the root password =="
passwd
read -rp "Create a user? (enter a name, or leave empty to skip): " USERNAME
if [[ -n "\$USERNAME" ]]; then
    useradd -m -G wheel "\$USERNAME"
    echo "== Set the password for \$USERNAME =="
    passwd "\$USERNAME"
    sed -i "s/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/" /etc/sudoers
fi
CHROOT_EOF
EOF
}
