#!/usr/bin/env bash
# decide/install.sh
# Generates the installation commands (run in QEMU, never on real hardware)

build_install_plan() {
    # Needs facts (./main.sh detect) and the decided package list (./main.sh decide)
    if [[ ! -f output/packages.txt ]]; then
        error "output/packages.txt not found — run './main.sh decide' first"
        return 1
    fi
    if [[ -z "${DISK_NAME:-}" || "${DISK_NAME:-}" == "none" ]]; then
        error "No disk detected — run './main.sh detect' first"
        return 1
    fi

    build_partitions >/dev/null # side effects only: fills DISK, FS_ROOT, SWAP_GB, PART_*

    local ucode=""
    case "${CPU_VENDOR:-unknown}" in
    amd) ucode="amd-ucode" ;;
    intel) ucode="intel-ucode" ;;
    esac

    # Decided packages (from the tree) + what any installer needs
    local pkgs extra="linux-firmware grub"
    pkgs=$(tr '\n' ' ' < output/packages.txt)
    [[ "${FIRMWARE:-uefi}" == "uefi" ]] && extra+=" efibootmgr"
    [[ "$FS_ROOT" == "btrfs" ]] && extra+=" btrfs-progs"

    # Locale/hostname/timezone: from facts.txt or env, safe defaults otherwise
    local tz="${TIMEZONE:-UTC}"
    local locale="${LOCALE:-en_US.UTF-8}"
    local hostname="${HOST_NAME:-arch}"

    local mkfs_cmd="mkfs.ext4 -F"
    [[ "$FS_ROOT" == "btrfs" ]] && mkfs_cmd="mkfs.btrfs -f"

    local bootloader_install="grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB"
    [[ "${FIRMWARE:-uefi}" == "bios" ]] && bootloader_install="grub-install --target=i386-pc $DISK"

    local services="NetworkManager"
    [[ "${HAS_BLUETOOTH:-no}" == "yes" ]] && services+=" bluetooth"
    [[ "${HAS_BATTERY:-no}" == "yes" ]] && services+=" tlp"

    cat <<EOF
#!/usr/bin/env bash
# Generated by cleiva_arch_installer — review it before running!
set -euo pipefail

# Safety: only run inside a VM
if [[ "\$(systemd-detect-virt)" == "none" ]]; then
    echo "Refusing to run outside a VM" >&2
    exit 1
fi

# Safety: never partition removable media (e.g. the USB stick you booted from)
if [[ "\$(lsblk -d -n -o RM "$DISK" 2>/dev/null)" == "1" ]]; then
    echo "Refusing: $DISK looks like removable media" >&2
    exit 1
fi

# 1. Partitions (${FIRMWARE:-uefi})
sgdisk --zap-all "$DISK"
EOF
    case "${FIRMWARE:-uefi}" in
    uefi)
        cat <<EOF
sgdisk -n1:0:+512M -t1:ef00 "$DISK"         # EFI system partition
sgdisk -n2:0:+${SWAP_GB}G -t2:8200 "$DISK"  # swap
sgdisk -n3:0:0 -t3:8300 "$DISK"             # root (rest)
EOF
        ;;
    bios)
        cat <<EOF
sgdisk -n1:0:+1M -t1:ef02 "$DISK"           # BIOS boot (grub)
sgdisk -n2:0:+${SWAP_GB}G -t2:8200 "$DISK"  # swap
sgdisk -n3:0:0 -t3:8300 "$DISK"             # root (rest)
EOF
        ;;
    esac
    cat <<EOF

# 2. Filesystems
$mkfs_cmd "$PART_ROOT"
mkswap "$PART_SWAP"
EOF
    if [[ "${FIRMWARE:-uefi}" == "uefi" ]]; then
        echo "mkfs.fat -F32 \"$PART_EFI\""
    fi
    cat <<EOF

# 3. Mount
mount "$PART_ROOT" /mnt
swapon "$PART_SWAP"
EOF
    if [[ "${FIRMWARE:-uefi}" == "uefi" ]]; then
        echo "mount --mkdir \"$PART_EFI\" /mnt/efi"
    fi
    cat <<EOF

# 4. Base system + decided packages
pacstrap -K /mnt ${pkgs}${extra}

# 5. fstab
genfstab -U /mnt >> /mnt/etc/fstab

# 6. Chroot configuration
arch-chroot /mnt /bin/bash -c '
set -euo pipefail
ln -sf /usr/share/zoneinfo/$tz /etc/localtime
hwclock --systohc
echo "$locale UTF-8" > /etc/locale.gen
locale-gen
echo "LANG=$locale" > /etc/locale.conf
echo "$hostname" > /etc/hostname
systemctl enable $services
$bootloader_install
grub-mkconfig -o /boot/grub/grub.cfg
echo "== Set the root password =="
passwd
read -rp "Create a user? (enter a name, or leave empty to skip): " USERNAME
if [[ -n "\$USERNAME" ]]; then
    useradd -m -G wheel "\$USERNAME"
    echo "== Set the password for \$USERNAME =="
    passwd "\$USERNAME"
    sed -i "s/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/" /etc/sudoers
fi
'
EOF
}
